src/api/urls.py
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView


urlpatterns = [
    url(r'^auth/login/$',
        obtain_auth_token,
        name='auth_user_login'),
    url(r'^auth/register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^auth/logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout')
]

src/fagar_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',include('users.urls')),
    path('',include('superuser.urls')),
    path('',include('sms_manager.urls')),
    path('',include('sms_manager.urls_many_companys')),
    path('',include('sms_manager.urls_mini_views')),
    path('',include('employees.urls')),
    path('',include('landing.urls')),
    url(r'api/', include('api.urls')),   
]

src/superuser/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    AdminDashboardView,
    AdminSmsManagerListView,
    AdminDetailSmsManagerView,
    AdminCreateSmsManagerView,
    AdminUpdateSmsManagerView,
    AdminCompanyListView,
    AdminDetailCompanyView,
    AdminCreateCompanyView,
    AdminUpdateCompanyView,
    AdminEmployeeListView,
    AdminDetailEmployeeView,
    AdminCreateEmployeeView,
)

app_name = 'superuser'

urlpatterns = [    
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('dashboard/sms-managers-list/', AdminSmsManagerListView.as_view(), name='sms-manager-list'),
    path('dashboard/sms-manager-detail/<int:id>/', AdminDetailSmsManagerView.as_view(), name='sms-manager-detail'),
    path('dashboard/sms-manager-create/', AdminCreateSmsManagerView.as_view(), name='sms-manager-create'),
    path('dashboard/sms-manager-update/<int:id>/', AdminUpdateSmsManagerView.as_view(), name='sms-manager-update'),
    path('dashboard/companys-list/', AdminCompanyListView.as_view(), name='company-list'),
    path('dashboard/comapny-detail/<int:id>/', AdminDetailCompanyView.as_view(), name='company-detail'),
    path('dashboard/company-create/', AdminCreateCompanyView.as_view(), name='company-create'),
    path('dashboard/company-update/<int:id>/', AdminUpdateCompanyView.as_view(), name='company-update'),
    path('dashboard/employees-list/', AdminEmployeeListView.as_view(), name='employee-list'),
    path('dashboard/employee-detail/<int:id>/', AdminDetailEmployeeView.as_view(), name='employee-detail'),
    path('dashboard/employee-create/', AdminCreateEmployeeView.as_view(), name='employee-create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,    
    )

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, reverse_lazy

from .views import (
    #SignupView,
	#SignupLinkSentView,
	#SignupActivationView,
	LoginView,
    LogoutView,    
    #CustomPasswordResetCompleteView,
)

app_name = 'users'

urlpatterns = [
    #URLS FOR SIGNUP PROCESS
    #path('signup/', SignupView.as_view(), name='signup'),
    #path('signup/linksent/', SignupLinkSentView.as_view(), name='signup-linksent'),
    #path('activation/<uid64>/<token>/', SignupActivationView.as_view(), name='signup-activation'),
    #URLS FOR LOGIN & LOGOUT
    path('login/', LoginView.as_view(), name='login'),       
    path('logout/', LogoutView.as_view(), name='logout'),
    #URLS FOR PASSWORD RESET
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done')
        ), name='password-reset'),
    path('password-reset-done/',PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
        ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
        ), name='password_reset_confirm'),
     #path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),    
]

src/superuser/models.py
from django.db import models

# Create your models here.

src/users/models.py
from django.db import models
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

from django.utils.translation import ugettext_lazy as _

from django.dispatch import receiver


#USERMANAGER esto para usar el correo electronico como identificador de usuario
class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)        
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

#Clase basica para tener varios tipos de usuarios
class User(AbstractBaseUser, PermissionsMixin):
    email           = models.EmailField(unique=True, blank=False)
    #flags que determinan el rol del usuario
    is_sms_manager	= models.BooleanField(default=False)
    is_employee	= models.BooleanField(default=False)
    #flag staff
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_('Do you think you can be a Superuser?'),
    )
    #flag staff
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    #falg activo
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )    
    
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

#Clase para los gerentes SMS
class SmsManager(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    #ci          = models.IntegerField(unique=True)
    career      = models.CharField(max_length=50, default='')     
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='sms_managers/profile_pics/', default='sms_managers/profile_pics/default_user_profile_pic.png')    

TYPE_OF_COMPANY = (
    ('1', 'Airport'),#Aeropuerto
    ('2', 'Aeroline'),#Personas Juridicas
    ('3', 'ciac'),#centro de instrucción
    ('4', 'omac'),#Taller OMAC    
)

class Company(models.Model):
    #todo compañia debe tener un gerente sms
    #tambien muchas compañias pueden tener un mismo gerete sms
    company_sms_manager = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='managed_by')
    name                = models.CharField(max_length=100)
    type_of_company     = models.CharField(max_length=1, choices=TYPE_OF_COMPANY, blank=True)
    #rav_type           = models.CharField(max_length=1, choices=TYPE_OF_RAP, blank=True)
    #una compañia puede tener mas de rav
    #hay regulaciones por otros paises rap (peru), far(estados unidos), etc
    #rav_number         = models.IntegerField(null=False, default=0)
    phone               = models.IntegerField(null=False, default=0)
    company_logo        = models.ImageField(upload_to='companys/company_logos/', default='companys/company_logos/default_company_logo.png')
    rif                 = models.IntegerField(null=False, default=0)
    company_mail        = models.EmailField(blank=False, default='mail@mail.com')

class Employee(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #muchos empleados pertenecen a una compañia
    company     = models.ForeignKey(Company, on_delete=models.CASCADE, related_name = 'employee_of_company', default = False)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='employees/profile_pics/', default='employess/profile_pics/default_user_profile_pic.png')    

TYPE_OF_RISK = (
    ('1', 'Relacionado con vuelo'),
    ('2', 'E.P.P. (Equipos de protección personal)'),
    ('3', 'Procedimientos'),
    ('4', 'Mantenimiento Aeronáutico'),
    ('5', 'FOD (Objetos extraños)'),
    ('6', 'Orden y limpieza'),
    ('7', 'Acto inseguro'),
    ('8', 'Otros'),
)

class RiskReport(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='reports_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)
    type_of_risk    = models.CharField(max_length=1, choices=TYPE_OF_RISK, blank=True)
    photo1          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo2          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo3          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo4          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo5          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    description     = models.TextField(blank=True)
    recmendations   = models.TextField(blank=True, default='')

class IncidentAccident(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incident_accident_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='incident_accident_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)    
    photo1          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo2          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo3          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo4          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo5          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    description     = models.TextField(blank=True)

src/superuser/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from users.models import User, Company

class SignupSmsManagerForm(UserCreationForm):
	email 		= forms.EmailField(max_length=300, help_text='Required')
	password1 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())
	password2 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())

	class Meta(UserCreationForm.Meta):
		model = User
		fields = ('email', 'password1', 'password2',)

    #Chequeamos que el mail no exista (ya registrado)
	def clean_email(self):
		# Get the email
		email = self.cleaned_data.get('email')

		# Check to see if any users already exist with this email as a username.
		try:
			match = User.objects.get(email=email)
		except User.DoesNotExist:
			# Unable to find a user, this is fine
			return email

		# A user was found with this as a username, raise an error.
		raise forms.ValidationError('This email address is already in use.')

	#Override clean method to check 
	def clean(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password1 != password2:			
			raise forms.ValidationError("The two password fields must match.")

		return self.cleaned_data

class SignupEmployeeForm(UserCreationForm):
	companys 	= forms.ModelChoiceField(queryset=Company.objects.all(), empty_label="Debe seleccionar una empresa")
	email 		= forms.EmailField(max_length=300, help_text='Required')
	password1 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())
	password2 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())

	class Meta(UserCreationForm.Meta):
		model = User
		fields = ('companys', 'email', 'password1', 'password2',)

    #Chequeamos que el mail no exista (ya registrado)
	def clean_email(self):
		# Get the email
		email = self.cleaned_data.get('email')

		# Check to see if any users already exist with this email as a username.
		try:
			match = User.objects.get(email=email)
		except User.DoesNotExist:
			# Unable to find a user, this is fine
			return email

		# A user was found with this as a username, raise an error.
		raise forms.ValidationError('Esta dirección de correo ya esta en uso')

	#Override clean method to check 
	def clean(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		"""if password1 and password1 != password2:			
			#raise forms.ValidationError("Las dos contraseñas deben coincidir")
			#raise forms.ValidationError({'password1': ["Passwords must be the same."]})"""

		return self.cleaned_data

class CreateCompanyForm(ModelForm):
	class Meta:
		model 	= Company
		fields 	= ('company_sms_manager','name', 'company_logo', 'type_of_company', 'phone', 'company_mail', 'rif')       

	""" #esto sirve para añadir class a un field del form
	def __init__(self, *args, **kwargs):
		super(CreateCompanyForm, self).__init__(*args, **kwargs)
		self.fields['company_logo'].widget.attrs\
			.update({                
				'class': 'file-path validate'
			})"""

src/superuser/templates/superuser/Admin-CompanyList.html
{% extends './AdminDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row company-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Prestadores de servicio</h3>
        </div>       
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="input-field">
            <i class="material-icons prefix">search</i>        
            <input type="text" placeholder="Busqueda por nombre, telefono, cedula o empresa">
        </div>
    </div>    
    <div class="row">
        <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'superuser:company-create' %}">
                <i class="material-icons">note_add</i>
            </a>
        </div>
        <div class="card br-5">
            <div class="card-content">                
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Empresa</th>                            
                            <th>Nombre</th>
                            <th>Tipo</th>
                            <th>Telefono</th>
                            <th>Correo</th>                            
                            <th>Gerente SMS A/C</th>
                            <th>Acción</th>
                        </tr>
                    </thead>    
                    <tbody>
                        {% for instance in companys.all %}
                        <tr>
                            <td><a href="{{ instance.company_logo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.company_logo.url }}" alt="Image Not Found"></a></td>                            
                            <td>{{ instance.name }}</td>
                            <td>
                                {% if instance.type_of_company == '1' %}
                                    Aeropuerto
                                {% endif %}
                                {% if instance.type_of_company == '2' %}
                                    Aerolinea
                                {% endif %}
                                {% if instance.type_of_company == '3' %}
                                    Ciac
                                {% endif %}
                                {% if instance.type_of_company == '4' %}
                                    Omac
                                {% endif %}
                            </td>
                            <td>{{ instance.phone }}</td>
                            <td>{{ instance.company_mail }}</td>                            
                            <td><a href="{{ instance.company_sms_manager.photo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.company_sms_manager.photo.url }}" alt="Image Not Found"></a></td>
                            <td>
                                <a href="{% url 'superuser:company-detail' instance.id %}" <i class="material-icons">remove_red_eye</i></a>
                                <a href="{% url 'superuser:company-update' instance.id %}" <i class="material-icons">edit</i></a>
                            </td>                            
                        </tr>                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/superuser/templates/superuser/Admin-EmployeeDetail.html
{% extends './AdminDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row employee-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Empleados</h3>
        </div>       
    </div>
</div>

<!--Employee BASIC DATA-->
<div class="row">
    <div class="container">
        <div class="valign-wrapper">
            <div class="row" style="width: 100%;">        
                <div class="col s12">
                    <div class="row text-center">
                        <h4>Información Basica</h4>
                    </div>    
                    <div class="card horizontal">                        
                        <div class="card-image">
                            <img src="{{ object.photo.url }}" class="profile-pic-medium mt-1 mb-1">
                            <!--<input type="file" name="photo" accept="image/*" id="id_photo" class="btn-edit-profile-pic" style="cursor: pointer; z-index: 10000; opacity: 0;">-->
                            <!--<a class="btn-edit-profile-pic btn-small btn-floating waves-effect waves-light grey darken-2" href="#SmsMangerProfilePicFormModal"><i class="material-icons">add_a_photo</i></a>-->
                            <button data-target="SmsMangerProfilePicFormModal" class="btn-edit-profile-pic btn-small btn-floating waves-effect waves-light grey darken-2 modal-trigger"><i class="material-icons">add_a_photo</i></button>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3>{{ object.name }} {{ object.last_name }}</h3>
                                <div class="divider"></div>
                                <br>
                                <p>{{ object.user.email }}</p>
                                <p>{{ object.phone }}</p>            
                            </div>                
                        </div>
                        <a class="btn-large btn-floating halfway-fab waves-effect waves-light green btn modal-trigger" href="#SmsMangerProfileFormModal"><i class="material-icons">edit</i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Employee Company-->
<div class="row">
    
<div class="container">
    <div class="row text-center">
        <h4>Trabaja en</h4>
    </div>
    <ul class="collection" style="margin-right: 24px;">                
        <li class="collection-item avatar">
            <img src="{{ object.company.company_logo.url }}" alt="" class="circle">
            <span class="title">{{ object.company.name }}</span>
            <p>
                <!--Firts Line Tipo de compañia-->
                {% if object.company.type_of_company == '1' %}
                    Aeropuerto<br>
                {% endif %}
                {% if object.company.type_of_company == '2' %}
                    Aerolinea<br>
                {% endif %}
                {% if object.company.type_of_company == '3' %}
                    Ciac<br>
                {% endif %}
                {% if object.company.type_of_company == '4' %}
                    Omac<br>
                {% endif %}
                <!--Second Line Telefono-->
                Telefono: {{ object.company.phone }}<br>
                <!--Third Line Email-->
                Email: {{ object.company.company_mail }}<br>
            </p>
            <a href="{% url 'superuser:company-detail' object.company.id %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>            
        </li>        
    </ul>
</div>
</div>

{% endblock %}

src/superuser/templates/superuser/Admin-EmployeeList.html
{% extends './AdminDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row employee-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Empleados</h3>
        </div>       
    </div>
</div>

<div class="container">
    <div class="row">        
        <div class="input-field">
            <i class="material-icons prefix">search</i>        
            <input type="text" placeholder="Busqueda por nombre, telefono, cedula o empresa">
        </div>
    </div>    
    <div class="row">
        <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'superuser:employee-create' %}">
                <i class="material-icons">person_add</i>
            </a>
        </div>
        <div class="card br-5">
            <div class="card-content">                
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Empresa</th>
                            <th>Mail</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Telefono</th>
                            <th>Acción</th>
                        </tr>
                    </thead>    
                    <tbody>
                        {% for instance in employees.all %}
                        <tr>
                            <td><a href="{{ instance.photo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.photo.url }}" alt="Image Not Found"></a></td>                                                        
                            <td><a class="tooltipped" data-tooltip="{{ instance.company.name }}" data-position="top" href="{{ instance.company.company_logo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.company.company_logo.url }}" alt="Image Not Found"></a></td>
                            <td>{{ instance.user }}</td>
                            <td>{{ instance.name }}</td>
                            <td>{{ instance.last_name }}</td>
                            <td>{{ instance.phone }}</td>
                            <td>
                                <a href="{% url 'superuser:employee-detail' instance.user.id %}" <i class="material-icons">remove_red_eye</i></a>
                            </td>
                        </tr>                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.tooltipped').tooltip();
    });
    </script>
{% endblock %}

src/superuser/templates/superuser/Admin-SmsManagerCreate.html
{% extends './AdminDashboard.html' %}
{% load static %}
{% block right-panel %}
<div class="row sms-manager-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Gerente SMS</h3>
        </div>       
    </div>
</div>

<div class="row">
<div class="col s4"></div>
<div class="col s4">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}">          
<div class="row">
    <div class="input-field col s12">    
        {{ form.email }}
        <label for="email">Email</label>
    </div>
</div>
        
<div class="row">
    <div class="input-field col s12">
        {{ form.password1 }}
        <label for="password">Contraseña</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        {{ form.password2 }}
        <label for="password">Repita la contraseña</label>
    </div>
</div>
<!--
<div class="row">
{% if form.errors %}
    <p class=" label label-danger">
        Your username and password didn't match. 
        Please try again.
    </p>
{% endif %}
</div>-->
<div class="row center">                    
    <input type='submit' class="waves-effect waves-light btn-large white-text" value='Crear Gerente SMS'>                    
</div>
</div>
<div class="col s4"></div>
</form>
</div>
{% endblock %}

src/superuser/templates/superuser/Admin-SmsManagerList.html
{% extends './AdminDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row sms-manager-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Gerentes SMS</h3>
        </div>       
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="input-field">
            <i class="material-icons prefix">search</i>        
            <input type="text" placeholder="Busqueda por nombre, telefono, cedula o empresa">
        </div>
    </div>    
    <div class="row">
        <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'superuser:sms-manager-create' %}">
                <i class="material-icons">person_add</i>
            </a>
        </div>
        <div class="card br-5">
            <div class="card-content">                
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Mail</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Telefono</th>
                            <th>Gestionando</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>    
                    <tbody>
                        {% for instance in sms_managers.all %}
                        <tr>
                            <td><a href="{{ instance.photo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.photo.url }}" alt="Image Not Found"></a></td>
                            <td>{{ instance.user }}</td>
                            <td>{{ instance.name }}</td>
                            <td>{{ instance.last_name }}</td>
                            <td>{{ instance.phone }}</td>
                            <td>{{ instance.managed_by.count }}</td>
                            <td>
                                <a href="{% url 'superuser:sms-manager-detail' instance.user.id %}" <i class="material-icons">remove_red_eye</i></a>
                                <a href="{% url 'superuser:sms-manager-update' instance.user.id %}" <i class="material-icons">edit</i></a>
                            </td>
                        </tr>                        
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/superuser/templates/superuser/LeftMenu.html
{% load static %}
<div class="green-material-square">
        <p><h1 class="right-align white-text">Bienvenido</h1></p>
        <p><h6 class="right-align">{{ user.email }}</h6></p>
      </div>
      <div>
        <ul class="collection principal-menu">          
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'superuser:sms-manager-list' %}">
              <i class="material-icons circle">person</i>
              Gerentes sms
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'superuser:company-list' %}">
              <i class="material-icons circle green">business</i>
              Prestadores de Servicio
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'superuser:employee-list' %}">
              <i class="material-icons circle red">group</i>
              Empleados
            </a>
          </li>                     
        </ul>
      </div>

src/superuser/templates/superuser/NavBar.html
<nav>
    <div class="nav-wrapper">
    <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
    <ul class="right hide-on-med-and-down">
        <li><a href="#!"><i class="material-icons">search</i></a></li>
        <li><a href="#!"><i class="material-icons">view_module</i></a></li>
        <li><a href="#!"><i class="material-icons">refresh</i></a></li>
        <li><a href="{% url 'users:logout' %}"><i class="material-icons right">exit_to_app</i>Salir</a></li>
    </ul>
    </div>
</nav>
        