src/api/urls.py
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView


urlpatterns = [
    url(r'^auth/login/$',
        obtain_auth_token,
        name='auth_user_login'),
    url(r'^auth/register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^auth/logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout')
]

src/fagar_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',include('users.urls')),
    path('',include('superuser.urls')),
    path('',include('sms_manager.urls')),
    path('',include('sms_manager.urls_many_companys')),
    path('',include('sms_manager.urls_mini_views')),
    path('',include('employees.urls')),
    path('',include('landing.urls')),
    url(r'api/', include('api.urls')),   
]

src/sms_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    SmsManagerDashboardView,
    SmsManagerProfileView,
    SmsManagerProfileUpdate,
    SmsManagerProfilePicUpdateView,
    SmsManagerRiskReportListView,
    SmsManagerRiskReportDetailView,    
    SmsManagerCreateRiskReportView,
    SmsManagerIncidentAccidentListView,
    SmsManagerIncidentAccidentDetailView,
    SmsManagerCreateIncidentAccidentView,
    SmsManagerEmployeeListView,
    SmsManagerDetailEmployeeView,
    SmsManagerCreateEmployeeView,    
)

app_name = 'sms_manager'

urlpatterns = [    
    path('sms-manager/dashboard/', SmsManagerDashboardView.as_view(), name='dashboard'),
    path('sms-manager/dashboard/profile/', SmsManagerProfileView.as_view(), name='profile-sms-manager'),
    path('sms-manager/dashboard/profile_update/', SmsManagerProfileUpdate.as_view(), name='update-profile-sms-manager'),
    path('sms-manager/dashboard/profile_pic_update/', SmsManagerProfilePicUpdateView.as_view(), name='update-profile-pic-sms-manager'),    
    path('sms-manager/dashboard/risk-report-list/', SmsManagerRiskReportListView.as_view(), name='risk-report-list'),
    path('sms-manager/dashboard/risk-report-detial/<int:id>/', SmsManagerRiskReportDetailView.as_view(), name='risk-report-detail'),
    path('sms-manager/dashboard/risk-report-create/', SmsManagerCreateRiskReportView.as_view(), name='risk-report-create'),
    path('sms-manager/dashboard/incident-accident-list/', SmsManagerIncidentAccidentListView.as_view(), name='incident-accident-list'),
    path('sms-manager/dashboard/incident-accident-detial/<int:id>/', SmsManagerIncidentAccidentDetailView.as_view(), name='incident-accident-detail'),
    path('sms-manager/dashboard/incident-accident-create/', SmsManagerCreateIncidentAccidentView.as_view(), name='incident-accident-create'),
    path('sms-manager/dashboard/employees-list/', SmsManagerEmployeeListView.as_view(), name='employee-list'),
    path('sms-manager/dashboard/employee-detail/<int:id>/', SmsManagerDetailEmployeeView.as_view(), name='employee-detail'),
    path('sms-manager/dashboard/employee-create/', SmsManagerCreateEmployeeView.as_view(), name='employee-create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,    
    )

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, reverse_lazy

from .views import (
    #SignupView,
	#SignupLinkSentView,
	#SignupActivationView,
	LoginView,
    LogoutView,    
    #CustomPasswordResetCompleteView,
)

app_name = 'users'

urlpatterns = [
    #URLS FOR SIGNUP PROCESS
    #path('signup/', SignupView.as_view(), name='signup'),
    #path('signup/linksent/', SignupLinkSentView.as_view(), name='signup-linksent'),
    #path('activation/<uid64>/<token>/', SignupActivationView.as_view(), name='signup-activation'),
    #URLS FOR LOGIN & LOGOUT
    path('login/', LoginView.as_view(), name='login'),       
    path('logout/', LogoutView.as_view(), name='logout'),
    #URLS FOR PASSWORD RESET
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done')
        ), name='password-reset'),
    path('password-reset-done/',PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
        ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
        ), name='password_reset_confirm'),
     #path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),    
]

src/sms_manager/models.py
from django.db import models

# Create your models here.

src/users/models.py
from django.db import models
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

from django.utils.translation import ugettext_lazy as _

from django.dispatch import receiver


#USERMANAGER esto para usar el correo electronico como identificador de usuario
class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)        
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

#Clase basica para tener varios tipos de usuarios
class User(AbstractBaseUser, PermissionsMixin):
    email           = models.EmailField(unique=True, blank=False)
    #flags que determinan el rol del usuario
    is_sms_manager	= models.BooleanField(default=False)
    is_employee	= models.BooleanField(default=False)
    #flag staff
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_('Do you think you can be a Superuser?'),
    )
    #flag staff
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    #falg activo
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )    
    
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

#Clase para los gerentes SMS
class SmsManager(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    #ci          = models.IntegerField(unique=True)
    career      = models.CharField(max_length=50, default='')     
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='sms_managers/profile_pics/', default='sms_managers/profile_pics/default_user_profile_pic.png')    

TYPE_OF_COMPANY = (
    ('1', 'Airport'),#Aeropuerto
    ('2', 'Aeroline'),#Personas Juridicas
    ('3', 'ciac'),#centro de instrucción
    ('4', 'omac'),#Taller OMAC    
)

class Company(models.Model):
    #todo compañia debe tener un gerente sms
    #tambien muchas compañias pueden tener un mismo gerete sms
    company_sms_manager = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='managed_by')
    name                = models.CharField(max_length=100)
    type_of_company     = models.CharField(max_length=1, choices=TYPE_OF_COMPANY, blank=True)
    #rav_type           = models.CharField(max_length=1, choices=TYPE_OF_RAP, blank=True)
    #una compañia puede tener mas de rav
    #hay regulaciones por otros paises rap (peru), far(estados unidos), etc
    #rav_number         = models.IntegerField(null=False, default=0)
    phone               = models.IntegerField(null=False, default=0)
    company_logo        = models.ImageField(upload_to='companys/company_logos/', default='companys/company_logos/default_company_logo.png')
    rif                 = models.IntegerField(null=False, default=0)
    company_mail        = models.EmailField(blank=False, default='mail@mail.com')

class Employee(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #muchos empleados pertenecen a una compañia
    company     = models.ForeignKey(Company, on_delete=models.CASCADE, related_name = 'employee_of_company', default = False)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='employees/profile_pics/', default='employess/profile_pics/default_user_profile_pic.png')    

TYPE_OF_RISK = (
    ('1', 'Relacionado con vuelo'),
    ('2', 'E.P.P. (Equipos de protección personal)'),
    ('3', 'Procedimientos'),
    ('4', 'Mantenimiento Aeronáutico'),
    ('5', 'FOD (Objetos extraños)'),
    ('6', 'Orden y limpieza'),
    ('7', 'Acto inseguro'),
    ('8', 'Otros'),
)

class RiskReport(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='reports_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)
    type_of_risk    = models.CharField(max_length=1, choices=TYPE_OF_RISK, blank=True)
    photo1          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo2          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo3          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo4          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo5          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    description     = models.TextField(blank=True)
    recmendations   = models.TextField(blank=True, default='')

class IncidentAccident(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incident_accident_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='incident_accident_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)    
    photo1          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo2          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo3          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo4          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo5          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    description     = models.TextField(blank=True)

src/sms_manager/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from users.models import User, SmsManager, RiskReport, Company, IncidentAccident

class SmsManagerProfileFormModal(forms.ModelForm):

    class Meta:
        model = SmsManager
        fields = ['name', 'last_name', 'phone']

class SmsManagerProfilePicFormModal(forms.ModelForm):

    class Meta:
        model = SmsManager
        fields = ['photo',]

#CREAR REPORTE DE RIESGO
class SmsManagerRiskReportForm(forms.ModelForm):

    class Meta:
        model = RiskReport
        fields = ['date', 'place', 'type_of_risk', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description', 'recmendations',]  
        """widgets = {
          'description': forms.Textarea(attrs={'rows':20, 'cols':15}),
        }"""

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(SmsManagerRiskReportForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })
        self.fields['recmendations'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

#CREAR INCIDENTE / ACCIDENTE
class SmsManagerIncidentAccidentForm(forms.ModelForm):

    class Meta:
        model = IncidentAccident
        fields = ['date', 'place', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description',]  

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(SmsManagerIncidentAccidentForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

#CREAR EMPLEADO
class SignupEmployeeForm(UserCreationForm):	
	email 		= forms.EmailField(max_length=300, help_text='Required')
	password1 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())
	password2 	= forms.CharField(label="",max_length=50,min_length=8, widget=forms.PasswordInput())

	class Meta(UserCreationForm.Meta):
		model = User
		fields = ('email', 'password1', 'password2',)

    #Chequeamos que el mail no exista (ya registrado)
	def clean_email(self):
		# Get the email
		email = self.cleaned_data.get('email')

		# Check to see if any users already exist with this email as a username.
		try:
			match = User.objects.get(email=email)
		except User.DoesNotExist:
			# Unable to find a user, this is fine
			return email

		# A user was found with this as a username, raise an error.
		raise forms.ValidationError('Esta dirección de correo ya esta en uso')

	#Override clean method to check 
	def clean(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		"""if password1 and password1 != password2:			
			#raise forms.ValidationError("Las dos contraseñas deben coincidir")
			#raise forms.ValidationError({'password1': ["Passwords must be the same."]})"""

		return self.cleaned_data

src/sms_manager/templates/sms_manager/LeftMenu.html
{% load static %}
<div class="green-material-square">
        <p><h1 class="right-align white-text">Bienvenido</h1></p>
        <p><h6 class="right-align">{{ user.email }}</h6></p>
      </div>
      <div>
        <ul class="collection principal-menu">
          <!--INICIO-->
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'sms_manager:dashboard' %}">
              <i class="material-icons circle blue">person_pin</i>
              Inicio
            </a>
          </li> 
          <!--PERFIL-->         
          <li class="collection-item avatar principal-menu-item">            
            {% if Manage_many == False %}
            <a href="{% url 'sms_manager:profile-sms-manager' %}">
              <i class="material-icons circle blue">person_pin</i>
              Perfil
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == False %}
            <a href="#modal1" class="modal-trigger">
              <i class="material-icons circle blue">person_pin</i>
              Perfil
            </a> 
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <a href="{% url 'sms_manager_many_companys:profile-sms-manager' company.id %}">
              <i class="material-icons circle blue">person_pin</i>
              Perfil
            </a>
            {% endif %}    
          </li>
          <!--REPORTES DE RIESGO-->         
          <li class="collection-item avatar principal-menu-item">
            {% if Manage_many == False %}
            <a href="{% url 'sms_manager:risk-report-list' %}">
              <i class="material-icons circle orange">report_problem</i>
              Reportes de Riesgo
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == False %}
            <a href="#modal1" class="modal-trigger">
              <i class="material-icons circle orange">report_problem</i>
              Reportes de Riesgo
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <a href="{% url 'sms_manager_many_companys:risk-report-list' company.id %}">
              <i class="material-icons circle orange">report_problem</i>
              Reportes de Riesgo
            </a>
            {% endif %}
          </li>
          <li class="collection-item avatar principal-menu-item">            
            {% if Manage_many == False %}
            <a href="{% url 'sms_manager:incident-accident-list' %}">
              <i class="material-icons circle red">report</i>
              Incidentes y Accidentes
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == False %}
            <a href="#modal1" class="modal-trigger">
              <i class="material-icons circle red">report</i>
              Incidentes y Accidentes
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <a href="{% url 'sms_manager_many_companys:incident-accident-list' company.id %}">
              <i class="material-icons circle red">report</i>
              Incidentes y Accidentes
            </a>
            {% endif %}
          </li>
          <li class="collection-item avatar principal-menu-item">
            {% if Manage_many == False %}
            <a href="#!">
              <i class="material-icons circle green">flight_takeoff</i>
              Reportes de Vuelo
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == False %}
            <a href="#modal1" class="modal-trigger">
              <i class="material-icons circle green">flight_takeoff</i>
              Reportes de Vuelo
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <a href="#!">
              <i class="material-icons circle green">flight_takeoff</i>
              Reportes de Vuelo
            </a>
            {% endif %}
          </li>
          <!--EMPLEADOS-->
          <li class="collection-item avatar principal-menu-item">
            {% if Manage_many == False %}
            <a href="{% url 'sms_manager:employee-list' %}">
              <i class="material-icons circle cyan">group</i>
              Empleados
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == False %}
            <a href="#modal1" class="modal-trigger">
              <i class="material-icons circle cyan">group</i>
              Empleados
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <a href="{% url 'sms_manager_many_companys:employee-list' company.id %}">
              <i class="material-icons circle cyan">group</i>
              Empleados
            </a>            
            {% endif %}
          </li>
            
          </li>                     
        </ul>
      </div>

src/sms_manager/templates/sms_manager/NavBar.html
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">Notificación 1</a></li>
    <li><a href="#!">Notificación 2</a></li>    
    <li><a href="#!">Notificación 3</a></li>
  </ul>
<!--Dropdown de prestadores de servicios-->

{% if Manage_many == True and select_a_company == True %}
<ul id="dropdown2" class="dropdown-content">    
    {% for company in companys %}  
    <li><a href="{% url 'sms_manager_many_companys:dashboard' company.id %}">{{ company.name }}</a></li>
    {% endfor %}
</ul>    
{% endif %}


<nav>
    <div class="nav-wrapper">
    <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
    <ul class="right hide-on-med-and-down">
        <li>
            {% if Manage_many == False %}
            <!--sin dropdown-->
            <a style="max-height: 64px; width: 105%;" href="#!" class="dropdown-trigger mr-2 tooltipped" data-position="bottom" data-tooltip="{{ company.name }}" id="ManagingCompany">
                Gestionando... &nbsp;&nbsp; <img style="max-height: 2rem; margin-top: 1.2rem; position: absolute;" src="{{ company.company_logo.url }}" alt="Image Not Found" class="circle">                
            </a>
            {% endif %}
            {% if Manage_many == True and select_a_company == True %}
            <!--con dropdowm dropdown-->
            <a style="max-height: 64px; width: 105%;" href="#!" class="dropdown-trigger mr-2 tooltipped" data-position="bottom" data-tooltip="{{ company.name }}" data-target="dropdown2" id="ManagingCompany">
                Gestionando... &nbsp;&nbsp; <img style="max-height: 2rem; margin-top: 1.2rem; position: absolute;" src="{{ company.company_logo.url }}" alt="Image Not Found" class="circle">
                <span class="material-icons right ml-1" style="margin-top: 1.2rem;">arrow_drop_down</span>
            </a>
            {% endif %}            
            
        </li>
        
        <!-- Dropdown Trigger -->
        <li>
            <a style="max-height: 64px;" class="dropdown-trigger" href="#!" data-target="dropdown1" id="ProfilePicAndNotifications">
                <!--Jquery Load here-->
            </a>
        </li>
        <li><a href="{% url 'users:logout' %}"><i class="material-icons right">exit_to_app</i>Salir</a></li>
    </ul>
    </div>
</nav>

src/sms_manager/templates/sms_manager/SmsManager-EmployeeList.html
{% extends './SmsManagerDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row employee-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Empleados</h3>
        </div>       
    </div>
</div>

<div class="container">
    <div class="row">        
        <div class="input-field">
            <i class="material-icons prefix">search</i>        
            <input type="text" placeholder="Busqueda por nombre, telefono, cedula o empresa">
        </div>
    </div>    
    <div class="row">
        <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'sms_manager:employee-create' %}">
                <i class="material-icons">person_add</i>
            </a>
        </div>
        <div class="card br-5">
            <div class="card-content">                
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Empresa</th>
                            <th>Mail</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Telefono</th>
                            <th>Acción</th>
                        </tr>
                    </thead>    
                    <tbody>
                        {% for instance in employees.all %}
                        <tr>
                            <td><a href="{{ instance.photo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.photo.url }}" alt="Image Not Found"></a></td>                                                        
                            <td><a class="tooltipped" data-tooltip="{{ instance.company.name }}" data-position="top" href="{{ instance.company.company_logo.url }}"><img style="max-height: 2rem; max-width: 5rem;" src="{{ instance.company.company_logo.url }}" alt="Image Not Found"></a></td>
                            <td>{{ instance.user }}</td>
                            <td>{{ instance.name }}</td>
                            <td>{{ instance.last_name }}</td>
                            <td>{{ instance.phone }}</td>
                            <td>
                                <a href="{% url 'sms_manager:employee-detail' instance.user.id %}" <i class="material-icons">remove_red_eye</i></a>
                            </td>
                        </tr>                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.tooltipped').tooltip();
    });
    </script>
{% endblock %}

src/sms_manager/templates/sms_manager/SmsManager-IncidentAccidentDetail.html
{% extends './SmsManagerDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row risk-report-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Incidente / Accidente</h3>
        </div>       
    </div>
</div>

<!--RISKREPORT BASIC DATA-->
<div class="row ml-2 mr-1">
    <div class="row">
        <!---->
        <div class="col s12 m2 card-panel grey lighten-5 z-depth-1" >
            <div class="valign-wrapper" style="width: 150px; height: 150px;">
                <p>
                    {{ object.date }} <br>
                    {{ object.place }} <br>                                          
                  </p>         
            </div>
          </div>
        <!--PRIMERA FOTO-->
        <div class="col s12 m2">
        <div class="card z-depth-2" style="width: 150px; height: 150px;">
            <div class="card-image">
            <img class="" style="width: 150px; height: 150px; background-size: cover; background-image: url({{ object.photo1.url }})">          
            </div>        
        </div>
        </div>
        <!--SEGUNDA FOTO-->
        <div class="col s12 m2">
            <div class="card z-depth-2" style="width: 150px; height: 150px;">
            <div class="card-image">
                <img class="" style="width: 150px; height: 150px; background-size: cover; background-image: url({{ object.photo2.url }})">          
            </div>        
            </div>
        </div>    
        <!--TERCERA FOTO-->
        <div class="col s12 m2">
            <div class="card z-depth-2" style="width: 150px; height: 150px;">
            <div class="card-image">
                <img class="" style="width: 150px; height: 150px; background-size: cover; background-image: url({{ object.photo3.url }})">          
            </div>        
            </div>
        </div>    
        <!--CUARTA FOTO-->
        <div class="col s12 m2">
            <div class="card z-depth-2" style="width: 150px; height: 150px;">
            <div class="card-image">
                <img class="" style="width: 150px; height: 150px; background-size: cover; background-image: url({{ object.photo4.url }})">          
            </div>        
            </div>
        </div>    
        <!--QUINTA FOTO-->
        <div class="col s12 m2">
            <div class="card z-depth-2" style="width: 150px; height: 150px;">
            <div class="card-image">
                <img class="" style="width: 150px; height: 150px; background-size: cover; background-image: url({{ object.photo5.url }})">          
            </div>        
            </div>
        </div>   
    </div>

    <div class="row">       
        <div class="col s4">            
            <div class="card small">
                <div class="card-image">
                  <img src="{{ reporter.photo.url }}">                  
                </div>
                <div class="card-content">
                  <p>
                    {% if sms_manager == True %}
                        <a href="{% url 'sms_manager:profile-sms-manager' %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>                
                    {% endif %}
                    {% if employee == True %}
                        <a href="{% url 'sms_manager:employee-detail' reporter.user_id %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>                
                    {% endif %}
                    {{ reporter.name }} {{ reporter.last_name }} <br>
                    {{ reporter.user }} <br>
                    {{ reporter.phone }}                    
                  </p>
                </div>                
              </div>
        </div>    
        <div class="col s8 pl-2">
            <div class="divider"></div> 
            <div class="row">
                <h5>Decripción:</h5>
                <p>{{ object.description }}<br></p>
            </div>
            <div class="divider"></div>
            <div class="row">
                <h5>Recomendaciones:</h5>
                <p>{{ object.recmendations }}<br></p>
            </div>
        </div>
    </div>  
</div>

{% endblock %}

src/sms_manager/templates/sms_manager/SmsMangerProfilePicFormModal.html
<form action="{% url 'sms_manager:update-profile-pic-sms-manager' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}        
    <div class="file-field input-field">
        <div class="btn">
            <span>Seleccionar Foto de Perfil</span>
            <input type="file" name="photo" accept="image/*" id="id_photo">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>
    <input type='submit' class="waves-effect waves-light btn-large white-text" value='Subir Foto'>
  </form>