src/api/urls.py
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView


urlpatterns = [
    url(r'^auth/login/$',
        obtain_auth_token,
        name='auth_user_login'),
    url(r'^auth/register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^auth/logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout')
]

src/employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy

from .views import (    	
    EmployeeDashboardView,
    EmployeeProfileView,
    EmployeeProfileUpdate, #for basic data
    EmployeeProfilePicUpdateView, #for only the profile picture
    EmployeeRiskReportListView, #El empleado solo debe ver los reportes hechos por el mismo
    EmployeeRiskReportDetailView,
    EmployeeCreateRiskReportView,
    EmployeeIncidentAccidentListView,
    EmployeeIncidentAccidentDetailView,
    EmployeeCreateIncidentAccidentView,
)

app_name = 'employees'

urlpatterns = [    
    path('employee/dashboard/', EmployeeDashboardView.as_view(), name='dashboard'),
    path('employee/dashboard/profile/', EmployeeProfileView.as_view(), name='profile-employee'),
    path('employee/dashboard/profile_update/', EmployeeProfileUpdate.as_view(), name='update-profile-employee'),
    path('employee/dashboard/profile_pic_update/', EmployeeProfilePicUpdateView.as_view(), name='update-profile-pic-employee'),    
    path('employee/dashboard/risk-report-list/', EmployeeRiskReportListView.as_view(), name='risk-report-list'),
    path('employee/dashboard/risk-report-detial/<int:id>/', EmployeeRiskReportDetailView.as_view(), name='risk-report-detail'),
    path('employee/dashboard/risk-report-create/', EmployeeCreateRiskReportView.as_view(), name='risk-report-create'),
    path('employee/dashboard/incident-accident-list/', EmployeeIncidentAccidentListView.as_view(), name='incident-accident-list'),
    path('employee/dashboard/incident-accident-detial/<int:id>/', EmployeeIncidentAccidentDetailView.as_view(), name='incident-accident-detail'),
    path('employee/dashboard/incident-accident-create/', EmployeeCreateIncidentAccidentView.as_view(), name='incident-accident-create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/fagar_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',include('users.urls')),
    path('',include('superuser.urls')),
    path('',include('sms_manager.urls')),
    path('',include('sms_manager.urls_many_companys')),
    path('',include('sms_manager.urls_mini_views')),
    path('',include('employees.urls')),
    path('',include('landing.urls')),
    url(r'api/', include('api.urls')),   
]

src/users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,    
    )

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, reverse_lazy

from .views import (
    #SignupView,
	#SignupLinkSentView,
	#SignupActivationView,
	LoginView,
    LogoutView,    
    #CustomPasswordResetCompleteView,
)

app_name = 'users'

urlpatterns = [
    #URLS FOR SIGNUP PROCESS
    #path('signup/', SignupView.as_view(), name='signup'),
    #path('signup/linksent/', SignupLinkSentView.as_view(), name='signup-linksent'),
    #path('activation/<uid64>/<token>/', SignupActivationView.as_view(), name='signup-activation'),
    #URLS FOR LOGIN & LOGOUT
    path('login/', LoginView.as_view(), name='login'),       
    path('logout/', LogoutView.as_view(), name='logout'),
    #URLS FOR PASSWORD RESET
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done')
        ), name='password-reset'),
    path('password-reset-done/',PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
        ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
        ), name='password_reset_confirm'),
     #path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),    
]

src/employees/models.py
from django.db import models

# Create your models here.

src/users/models.py
from django.db import models
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

from django.utils.translation import ugettext_lazy as _

from django.dispatch import receiver


#USERMANAGER esto para usar el correo electronico como identificador de usuario
class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)        
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

#Clase basica para tener varios tipos de usuarios
class User(AbstractBaseUser, PermissionsMixin):
    email           = models.EmailField(unique=True, blank=False)
    #flags que determinan el rol del usuario
    is_sms_manager	= models.BooleanField(default=False)
    is_employee	= models.BooleanField(default=False)
    #flag staff
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_('Do you think you can be a Superuser?'),
    )
    #flag staff
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    #falg activo
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )    
    
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

#Clase para los gerentes SMS
class SmsManager(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    #ci          = models.IntegerField(unique=True)
    career      = models.CharField(max_length=50, default='')     
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='sms_managers/profile_pics/', default='sms_managers/profile_pics/default_user_profile_pic.png')    

TYPE_OF_COMPANY = (
    ('1', 'Airport'),#Aeropuerto
    ('2', 'Aeroline'),#Personas Juridicas
    ('3', 'ciac'),#centro de instrucción
    ('4', 'omac'),#Taller OMAC    
)

class Company(models.Model):
    #todo compañia debe tener un gerente sms
    #tambien muchas compañias pueden tener un mismo gerete sms
    company_sms_manager = models.ForeignKey(SmsManager, on_delete=models.CASCADE, related_name='managed_by')
    name                = models.CharField(max_length=100)
    type_of_company     = models.CharField(max_length=1, choices=TYPE_OF_COMPANY, blank=True)
    #rav_type           = models.CharField(max_length=1, choices=TYPE_OF_RAP, blank=True)
    #una compañia puede tener mas de rav
    #hay regulaciones por otros paises rap (peru), far(estados unidos), etc
    #rav_number         = models.IntegerField(null=False, default=0)
    phone               = models.IntegerField(null=False, default=0)
    company_logo        = models.ImageField(upload_to='companys/company_logos/', default='companys/company_logos/default_company_logo.png')
    rif                 = models.IntegerField(null=False, default=0)
    company_mail        = models.EmailField(blank=False, default='mail@mail.com')

class Employee(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    #muchos empleados pertenecen a una compañia
    company     = models.ForeignKey(Company, on_delete=models.CASCADE, related_name = 'employee_of_company', default = False)
    name        = models.CharField(max_length=50)
    last_name   = models.CharField(max_length=50)    
    phone       = models.IntegerField(null=False, default=0)
    photo       = models.ImageField(upload_to='employees/profile_pics/', default='employess/profile_pics/default_user_profile_pic.png')    

TYPE_OF_RISK = (
    ('1', 'Relacionado con vuelo'),
    ('2', 'E.P.P. (Equipos de protección personal)'),
    ('3', 'Procedimientos'),
    ('4', 'Mantenimiento Aeronáutico'),
    ('5', 'FOD (Objetos extraños)'),
    ('6', 'Orden y limpieza'),
    ('7', 'Acto inseguro'),
    ('8', 'Otros'),
)

class RiskReport(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='reports_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)
    type_of_risk    = models.CharField(max_length=1, choices=TYPE_OF_RISK, blank=True)
    photo1          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo2          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo3          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo4          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    photo5          = models.ImageField(upload_to='risk_reports/', default='risk_reports/risk.png')
    description     = models.TextField(blank=True)
    recmendations   = models.TextField(blank=True, default='')

class IncidentAccident(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incident_accident_of_owner')
    of_company      = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='incident_accident_of_company')
    date            = models.DateField()
    place           = models.CharField(max_length=100)    
    photo1          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo2          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo3          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo4          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    photo5          = models.ImageField(upload_to='incidents_accidents/', default='incidents_accidents/incident_accident.jpg')
    description     = models.TextField(blank=True)

src/employees/forms.py
from django import forms
from users.models import SmsManager, RiskReport, Employee, IncidentAccident

class EmployeeProfileFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['name', 'last_name', 'phone']

class EmployeePicFormModal(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['photo',]


class EmployeeRiskReportForm(forms.ModelForm):

    class Meta:
        model = RiskReport
        fields = ['date', 'place', 'type_of_risk', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description', 'recmendations',]  
        """widgets = {
          'description': forms.Textarea(attrs={'rows':20, 'cols':15}),
        }"""

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeRiskReportForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })
        self.fields['recmendations'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

class EmployeeIncidentAccidentForm(forms.ModelForm):

    class Meta:
        model = IncidentAccident
        fields = ['date', 'place', 'photo1', 'photo2', 'photo3', 'photo4', 'photo5', 'description',]        

    #esto sirve para añadir class a un field del form
    def __init__(self, *args, **kwargs):
        super(EmployeeIncidentAccidentForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs\
            .update({                
                'class': 'materialize-textarea'
            })

src/employees/templates/employee/Employee-IncidentAccidentCreate.html
{% extends './EmployeeDashboard.html' %}
{% load static %}
{% block right-panel %}
<div class="row risk-report-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Crear Reporte Incidente / Accidente</h3>
        </div>       
    </div>
</div>

<div class="row">
<div class="col s2"></div>
<div class="col s8">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

<div class="row">
    <div class="input-field col s12">    
        <input type="text" name="date" required="" id="id_date" class="datepicker">
        <label for="date">Selecciona una fecha</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">    
        {{ form.place }}
        <label>Lugar:</label>
    </div>
</div>

<div class="row">
    <div class="col s12">        
        <label>Opcionalmente puede agregar hasta 5 fotos asociadas al incidente o accidente</label>
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 1:</span>
        <input type="file" name="photo1" accept="image/*" id="id_photo1">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 2:</span>
        <input type="file" name="photo2" accept="image/*" id="id_photo2">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 3:</span>
        <input type="file" name="photo3" accept="image/*" id="id_photo3">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 4:</span>
        <input type="file" name="photo4" accept="image/*" id="id_photo4">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 5:</span>
        <input type="file" name="photo5" accept="image/*" id="id_photo5">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        {{ form.description }}
        <label>Descripción:</label>
    </div>
</div>

<div class="row center">                    
    <input type='submit' class="waves-effect waves-light btn-large white-text" value='Crear Reporte Incidente / Accidente'>                    
</div>
</div>
<div class="col s2"></div>
</form>
</div>

<!--SCRIPTS-->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('select').formSelect();
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            i18n: {
                months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic"],
                weekdays: ["Domingo","Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
                weekdaysShort: ["Dom","Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
                weekdaysAbbrev: ["D","L", "M", "M", "J", "V", "S"],
                today: 'Hoy',
		        clear: 'Limpiar',
		        close: 'Ok',
                cancel: 'Cancelar',
		        labelMonthNext: 'Siguiente mes',
			    labelMonthPrev: 'Mes anterior',			    
            }
        });                
    });        
</script>
{% endblock %}

src/employees/templates/employee/Employee-IncidentAccidentList.html
{% extends './EmployeeDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="row risk-report-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Incidentes / Accidentes </h3>
        </div>       
    </div>
</div>

<div class="container">
        <div class="row">
            <div class="input-field">
                <i class="material-icons prefix">search</i>        
                <input type="text" placeholder="Busqueda por nombre, telefono, cedula o empresa">
            </div>
        </div>    
        <div class="row">
            <div class="fixed-action-btn">
                <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'employees:incident-accident-create' %}">
                    <i class="material-icons">add_alert</i>
                </a>
            </div>
            
            <div>

  <ul class="collection">
    {% for instance in incidents_accidents.all %}
    <li class="collection-item avatar">
      <img src="{{ instance.photo1.url }}" alt="Image Not Found" class="" style="max-width: 3rem; position: absolute; left: 1rem;">
      <span class="title">{{ instance.date }}</span>
      <p class="colecction-elipsis-text">
        {{ instance.place }} <br>                
        {{ instance.description }}<br>
      </p>
      <a href="{% url 'employees:incident-accident-detail' instance.id %}" class="secondary-content"><i class="material-icons">remove_red_eye</i></a>
    </li>
    {% endfor %}
  </ul>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.tooltipped').tooltip();
    });
    </script>

{% endblock %}

src/employees/templates/employee/Employee-RiskReportCreate.html
{% extends './EmployeeDashboard.html' %}
{% load static %}
{% block right-panel %}
<div class="row risk-report-background">
    <div class="overlay-banner white-text">                
        <div class="valign-wrapper">   
            <h3 class="ml-2">Crear Reporte de riesgo</h3>
        </div>       
    </div>
</div>

<div class="row">
<div class="col s1"></div>
<div class="col s9">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

<div class="row">
    <div class="input-field col s12">    
        <input type="text" name="date" required="" id="id_date" class="datepicker">
        <label for="date">Selecciona una fecha</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">    
        {{ form.place }}
        <label>Lugar:</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        {{ form.type_of_risk }}
        <label>Tipo de riesgo:</label>
    </div>
</div>

<div class="row">
    <div class="col s12">        
        <label>Opcionalmente puede agregar hasta 5 fotos asociadas al reporte de riesgo</label>
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 1:</span>
        <input type="file" name="photo1" accept="image/*" id="id_photo1">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 2:</span>
        <input type="file" name="photo2" accept="image/*" id="id_photo2">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 3:</span>
        <input type="file" name="photo3" accept="image/*" id="id_photo3">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 4:</span>
        <input type="file" name="photo4" accept="image/*" id="id_photo4">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="file-field input-field">
    <div class="btn">
        <span>Foto 5:</span>
        <input type="file" name="photo5" accept="image/*" id="id_photo5">
    </div>
    <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        {{ form.description }}
        <label>Descripción:</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        {{ form.recmendations }}
        <label>Recomendaciones:</label>
    </div>
</div>



<div class="row center">                    
    <input type='submit' class="waves-effect waves-light btn-large white-text" value='Crear Reporte de Riesgo'>                    
</div>
</div>
<div class="col s1"></div>
</form>
</div>

<!--SCRIPTS-->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('select').formSelect();
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            i18n: {
                months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic"],
                weekdays: ["Domingo","Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
                weekdaysShort: ["Dom","Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
                weekdaysAbbrev: ["D","L", "M", "M", "J", "V", "S"],
                today: 'Hoy',
		        clear: 'Limpiar',
		        close: 'Ok',
                cancel: 'Cancelar',
		        labelMonthNext: 'Siguiente mes',
			    labelMonthPrev: 'Mes anterior',			    
            }
        });                
    });        
</script>
{% endblock %}

src/employees/templates/employee/EmployeeDashboardProfile.html
{% extends './EmployeeDashboard.html' %}
{% load static %}
{% block right-panel %}

<div class="container">
    <div class="valign-wrapper full-height">
        <div class="row" style="width: 100%;">        
            <div class="col s12">    
                <div class="card horizontal">
                    <div class="card-image">
                        <img src="{{ object.photo.url }}" class="profile-pic-medium mt-1 mb-1">
                        <!--<input type="file" name="photo" accept="image/*" id="id_photo" class="btn-edit-profile-pic" style="cursor: pointer; z-index: 10000; opacity: 0;">-->
                        <!--<a class="btn-edit-profile-pic btn-small btn-floating waves-effect waves-light grey darken-2" href="#SmsMangerProfilePicFormModal"><i class="material-icons">add_a_photo</i></a>-->
                        <button data-target="SmsMangerProfilePicFormModal" class="btn-edit-profile-pic btn-small btn-floating waves-effect waves-light grey darken-2 modal-trigger"><i class="material-icons">add_a_photo</i></button>
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <h3>{{ object.name }} {{ object.last_name }}</h3>
                            <div class="divider"></div>
                            <br>
                            <p>{{ object.user.email }}</p>
                            <p>{{ object.phone }}</p>            
                        </div>                
                    </div>
                    <a class="btn-large btn-floating halfway-fab waves-effect waves-light green btn modal-trigger" href="#SmsMangerProfileFormModal"><i class="material-icons">edit</i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Formulario datos basicos -->
<div id="SmsMangerProfileFormModal" class="modal">
    <div class="modal-content" id="update-profile-url">
        {% include './EmployeeProfileFormModal.html' %}
    </div>
</div>
<!-- Modal Formulario foto de perfil -->
<div id="SmsMangerProfilePicFormModal" class="modal">
    <div class="modal-content" id="update-profile-pic-url">
        {% include './EmployeeProfilePicFormModal.html' %}
    </div>
</div>
<!--SCRIPTS-->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript">
    $( document ).ready(function() {        
        $('.modal').modal();
        $('#update-profile-url').load("{% url 'employees:update-profile-employee' %}");             
        $('#update-profile-pic-url').load("{% url 'employees:update-profile-pic-employee' %}");
    });
</script>
{% endblock %}

src/employees/templates/employee/EmployeeProfilePicFormModal.html
<form action="{% url 'employees:update-profile-pic-employee' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}        
    <div class="file-field input-field">
        <div class="btn">
            <span>Seleccionar Foto de Perfil</span>
            <input type="file" name="photo" accept="image/*" id="id_photo">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>
    <input type='submit' class="waves-effect waves-light btn-large white-text" value='Subir Foto'>
</form>

src/employees/templates/employee/LeftMenu.html
{% load static %}
<div class="green-material-square">
        <p><h1 class="right-align white-text">Bienvenido</h1></p>
        <p><h6 class="right-align">{{ user.email }}</h6></p>
      </div>
      <div>
        <ul class="collection principal-menu">
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'employees:dashboard' %}">
              <i class="material-icons circle blue">person_pin</i>
              Inicio
            </a>
          </li>          
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'employees:profile-employee' %}">
              <i class="material-icons circle blue">person_pin</i>
              Perfil
            </a>
          </li>          
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'employees:risk-report-list' %}">
              <i class="material-icons circle orange">report_problem</i>
              Reportes de Riesgo
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="{% url 'employees:incident-accident-list' %}">
              <i class="material-icons circle red">report</i>
              Incidentes y Accidentes
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle green">flight_takeoff</i>
              Reportes de Vuelo
            </a>
          </li>                     
        </ul>
      </div>

src/employees/templates/employee/NavBar.html
<nav>
    <div class="nav-wrapper">
    <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
    <ul class="right hide-on-med-and-down">
        <li><a href="#!"><i class="material-icons">search</i></a></li>
        <li><a href="#!"><i class="material-icons">view_module</i></a></li>
        <li><a href="#!"><i class="material-icons">refresh</i></a></li>
        <li><a href="{% url 'users:logout' %}"><i class="material-icons right">exit_to_app</i>Salir</a></li>
    </ul>
    </div>
</nav>
        