src/api/urls.py
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView


urlpatterns = [
    url(r'^auth/login/$',
        obtain_auth_token,
        name='auth_user_login'),
    url(r'^auth/register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^auth/logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout')
]

src/fagar_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',include('users.urls')),
    path('',include('superuser.urls')),
    path('',include('sms_manager.urls')),
    path('',include('sms_manager.urls_many_companys')),
    path('',include('sms_manager.urls_mini_views')),
    path('',include('employees.urls')),
    path('',include('landing.urls')),
    url(r'api/', include('api.urls')),   
]

src/landing/urls.py
from django.urls import path
from .views import (
    LandingView,
    #AboutView,
    #ContactView,
    #FAQView,
    #PricingView,
)

app_name = 'landing'

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    #path('about/', AboutView.as_view(), name='about'),
    #path('contact/', ContactView.as_view(), name='contact'),
    #path('faq/', FAQView.as_view(), name='faq'),
    #path('pricing/', PricingView.as_view(), name='pricing'),
]

src/users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,    
    )

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include, reverse_lazy

from .views import (
    #SignupView,
	#SignupLinkSentView,
	#SignupActivationView,
	LoginView,
    LogoutView,    
    #CustomPasswordResetCompleteView,
)

app_name = 'users'

urlpatterns = [
    #URLS FOR SIGNUP PROCESS
    #path('signup/', SignupView.as_view(), name='signup'),
    #path('signup/linksent/', SignupLinkSentView.as_view(), name='signup-linksent'),
    #path('activation/<uid64>/<token>/', SignupActivationView.as_view(), name='signup-activation'),
    #URLS FOR LOGIN & LOGOUT
    path('login/', LoginView.as_view(), name='login'),       
    path('logout/', LogoutView.as_view(), name='logout'),
    #URLS FOR PASSWORD RESET
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done')
        ), name='password-reset'),
    path('password-reset-done/',PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
        ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
        ), name='password_reset_confirm'),
     #path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),    
]

src/landing/models.py
from django.db import models

# Create your models here.

src/landing/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    ListView,
    DeleteView,
    FormView
)

import json

class LandingView(View):
    template_name = "landing/LandingBase.html"

    def get(self, request, *args, **kwargs):
        # GET method
        context={}                
        return render(request, self.template_name, context)

src/landing/templates/landing/LandingBase.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--GoogleFont-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--MaterializeCss-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %} "  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/landing.css' %} "  media="screen,projection"/>
    <title>Fagar-sms</title>
</head>
<body>
  <div class="row mb-0">
    <div class="col s3 principal-colum">
      <div class="green-material-square">
        <p><h1 class="right-align white-text">Fagar-<span class="white-text">SMS</span></h1></p>
        <p><h6 class="right-align">Por Aeroservicios fagar</h6></p>
      </div>
      <div>
        <ul class="collection principal-menu">          
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle green">monetization_on</i>
              Servicios Y Tarifas
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle blue">group</i>
              Quienes Somos
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle black">phone_iphone</i>
              Aplicación Movil
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle red">contacts</i>
              Contacto
            </a>
          </li>
          <li class="collection-item avatar principal-menu-item">
            <a href="#!">
              <i class="material-icons circle cyan">speaker_notes</i>
              Preguntas Frecuentes
            </a>
          </li>           
        </ul>
      </div>
    </div>  
    <div id="airport-background" class="col s9">
      <div class="overlay white-text">        
        <div class="container">
          <div class="valign-wrapper full-height">
            <row>
              <h1>Gestion de la Seguridad Operacional</h1>
              <h2>A su alcance <a href="{% url 'users:login' %}" class="waves-effect waves-light btn-large"><i class="material-icons left">airplanemode_active</i>Iniciar</a></h2>
            </row>
          </div>
        </div>       
      </div>      
    </div>
  </div>  
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>